basis = "Algemene informatie over het document: bedrijf, datum, leveringsconditie,..."
totaalIncl = "het totaalbedrag van deze factuur of offerte, btw inbegrepen. Zonder het eenheidssymbool"
munteenheid = "De munteenheid van alle prijzen in dit document"
documentNummer = "unieke identificatie voor dit document"
documentDatum = "De datum waarop dit document is opgesteld"
lijnitems = "Een lijst van alle producten of diensten in dit document"
raw= "the full received text. No alterations additions or exclusions are done to this."